sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

cache:
  directories:
      - $HOME/.cache/pip

install:
    - pip install travis-sphinx sphinx
    - pip install -e . 

script:
    - python setup.py test
