name: Build

on:
  push:
    branches: '*'
    tags: 'v*'
  pull_request:
    branches: '*'

jobs:
  build-linux:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Create binary
      run: |
        pip install .
        pip install pyinstaller==4.3
        pyinstaller ./teamscale_precommit_client/precommit_client.py --onefile -path ./teamscale_precommit_client --name teamscale-cli
        chmod +x ./dist/teamscale-cli
      # - name: Create binary
      #   uses: JackMcKew/pyinstaller-action-linux@0.1.4
      #   with:
      #     path: teamscale_precommit_client
      #     spec: precommit_client.spec
    - name: 'Upload Artifact'
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: teamscale-cli-linux
        path: ./dist/teamscale-cli
        retention-days: 5

